### ISSUE TITLE
Deploy collator monitoring script

### ISSUE THREAD

**Issue by bogdanS98** [pendulum-chain/collator-monitoring#3]
This script should run as a cron job once a week.

# How to build and run 

## Prerequisites
The script needs to have Node.js installed. 

### Environment variables
We also need to define the following environment variables. They can be put into a local `.env` file, supplied when running the last command (ie. `SLACK_WEB_HOOK_TOKEN="xxx" ... node ./dist/index.js`) or sourced into the shell.

- `SLACK_WEB_HOOK_TOKEN` - Slack web hook token for collator perfromance reporting.

#### Optional

- `PERCENTAGE` - The percentage of the average number of blocks authored per collator in 24 hours which is considered to be acceptable collator performance. Defaults to `75`.

### Deployment
```
# Clone the repository (main branch)
git clone https://github.com/pendulum-chain/collator-monitoring.git

# Change directories
cd collator-monitoring

# Install the dependencies
npm install

# Build the files
npm run build

# Run the service
node ./dist/index.js
```

**Comment by ebma** [comment]
@zoveress can you please take care of this deployment? If there are any questions let us know.

**Comment by prayagd** [comment]
@ebma this is done right, resulting in the messages we see in the devops chat right?

**Comment by ebma** [comment]
Yes, I think we can close this ticket. Thanks for deploying it @zoveress 👍
